<a href="https://colab.research.google.com/github/jhajagos/SupportingConceptSetGeneration/blob/main/Build_ICD10CM_tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pyspark
import pandas as pd
import pyspark.sql.functions as F

## Comorbidities

### ICD10CM Codes

In [2]:
icd10_code_df = pd.read_csv("https://raw.githubusercontent.com/jhajagos/SupportingConceptSetGeneration/refs/heads/main/comorbidities/data/generated_from_nb/comorbiditiesR/icd10cm_to_map_codes.csv")
icd10_code_df

        Code                                        Description     id
0       A000  Cholera due to Vibrio cholerae 01, biovar chol...      1
1       A001    Cholera due to Vibrio cholerae 01, biovar eltor      2
2       A009                               Cholera, unspecified      3
3      A0100                         Typhoid fever, unspecified      4
4      A0101                                 Typhoid meningitis      5
...      ...                                                ...    ...
72745  Z9981                  Dependence on supplemental oxygen  72746
72746  Z9989  Dependence on other enabling machines and devices  72747
72747   U070                            Vaping-related disorder  72748
72748   U071                                           COVID-19  72749
72749   U099               Post COVID-19 condition, unspecified  72750

[72750 rows x 3 columns]

In [3]:
icd10_code_df[["Code"]].drop_duplicates()

        Code
0       A000
1       A001
2       A009
3      A0100
4      A0101
...      ...
72745  Z9981
72746  Z9989
72747   U070
72748   U071
72749   U099

[72750 rows x 1 columns]

In [4]:
icd10_code_df[["Code", "Description"]].drop_duplicates()

        Code                                        Description
0       A000  Cholera due to Vibrio cholerae 01, biovar chol...
1       A001    Cholera due to Vibrio cholerae 01, biovar eltor
2       A009                               Cholera, unspecified
3      A0100                         Typhoid fever, unspecified
4      A0101                                 Typhoid meningitis
...      ...                                                ...
72745  Z9981                  Dependence on supplemental oxygen
72746  Z9989  Dependence on other enabling machines and devices
72747   U070                            Vaping-related disorder
72748   U071                                           COVID-19
72749   U099               Post COVID-19 condition, unspecified

[72750 rows x 2 columns]

In [5]:
icd10_code_df[["Code", "Description"]].groupby("Code").agg("count").reset_index().sort_values(by="Description", ascending=False)

        Code  Description
72749  Z9989            1
0       A000            1
1       A001            1
2       A009            1
3      A0100            1
...      ...          ...
18     A0222            1
17     A0221            1
16     A0220            1
15      A021            1
14      A020            1

[72750 rows x 2 columns]

### Charlson index

In [6]:
charlson_df = pd.read_csv("https://raw.githubusercontent.com/jhajagos/SupportingConceptSetGeneration/refs/heads/main/comorbidities/data/generated_from_nb/comorbiditiesR/icd10_cm_map_charl.csv")
charlson_df

,id,mi,chf,pvd,cevd,dementia,cpd,rheumd,pud,mld,diab,diabwc,hp,rend,canc,msld,metacanc,aids
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72745,72746,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
72746,72747,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
72747,72748,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
72748,72749,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
72749,72750,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [8]:
charlson_merged_df = pd.merge(icd10_code_df, charlson_df, on='id')

### Elixhauser index

In [7]:
elix_hauser_df = pd.read_csv("https://raw.githubusercontent.com/jhajagos/SupportingConceptSetGeneration/refs/heads/main/comorbidities/data/generated_from_nb/comorbiditiesR/icd10_cm_map_elix.csv")
elix_hauser_df

,id,chf,carit,valv,pcd,pvd,hypunc,hypc,para,ond,...,coag,obes,wloss,fed,blane,dane,alcohol,drug,psycho,depre
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72745,72746,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72746,72747,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72747,72748,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72748,72749,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72749,72750,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
elix_hauser_merged_df = pd.merge(icd10_code_df, elix_hauser_df, on='id')

In [10]:
elix_hauser_merged_df

,Code,Description,id,chf,carit,valv,pcd,pvd,hypunc,hypc,...,coag,obes,wloss,fed,blane,dane,alcohol,drug,psycho,depre
0,A000,"Cholera due to Vibrio cholerae 01, biovar chol...",1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor",2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,A009,"Cholera, unspecified",3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,A0100,"Typhoid fever, unspecified",4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,A0101,Typhoid meningitis,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72745,Z9981,Dependence on supplemental oxygen,72746,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72746,Z9989,Dependence on other enabling machines and devices,72747,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72747,U070,Vaping-related disorder,72748,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72748,U071,COVID-19,72749,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72749,U099,"Post COVID-19 condition, unspecified",72750,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Load the UMLS

In [11]:
spark = pyspark.sql.SparkSession.builder.appName('UMLS').config("spark.driver.memory", "16g").getOrCreate()

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
UMLS_OUTPUT_DIRECTORY = "/content/drive/MyDrive/umls/2025AA/export/"

In [14]:
import json

In [15]:
with open(UMLS_OUTPUT_DIRECTORY + "umls_generated_tables.json") as f:
  tables = json.load(f)

In [16]:
def load_tables(sptr, metadata_dict, domains_to_load=["ohdsi", "concept", "prepared_source"]):
  sdf_dict = {}
  for domain in domains_to_load:
    print(f"Loading domain: {domain}")
    for table in metadata_dict[domain]:
      print(f"Loading table: {table}")
      sdf_dict[table] = sptr.read.parquet(metadata_dict[domain][table])
      sdf_dict[table].createOrReplaceTempView(table)
  return sdf_dict

In [17]:
td = load_tables(spark, tables, ["umls"])

Loading domain: umls
Loading table: MRCONSO
Loading table: MRHIER
Loading table: MRDEF
Loading table: MRSAB
Loading table: MRSAT
Loading table: MRREL
Loading table: MRSTY
Loading table: MRCOLS
Loading table: MRCUI

### ICD10CM PT (Preferred terms; codable)

In [18]:
umls_icd10_pt_sdf = spark.sql("""
with stys (
  select CUI, collect_list(STY) as STYs from MRSTY s group by CUI
)
select c.*, stys.STYs
  from MRCONSO c
    join stys on stys.CUI = c.CUI
where SAB='ICD10CM' and TTY in ('PT')""")
umls_icd10_pt_df = umls_icd10_pt_sdf.toPandas()
umls_icd10_pt_df["PREFIX_CODE"] = umls_icd10_pt_df["CODE"].str.slice(stop=3)
umls_icd10_pt_df

,CUI,LAT,TS,LUI,STT,SUI,ISPREF,AUI,SAUI,SCUI,...,SAB,TTY,CODE,STR,SRL,SUPPRESS,CVF,dummy,STYs,PREFIX_CODE
0,C0000814,ENG,P,L0000814,PF,S0218595,N,A17815492,NaN,None,...,ICD10CM,PT,O02.1,Missed abortion,4,N,256.0,None,[Disease or Syndrome],O02
1,C0001145,ENG,P,L0001145,VC,S0798036,N,A17839636,NaN,None,...,ICD10CM,PT,L73.0,Acne keloid,4,N,256.0,None,[Disease or Syndrome],L73
2,C0001171,ENG,P,L0001171,PF,S0218783,N,A17866282,NaN,None,...,ICD10CM,PT,M95.4,Acquired deformity of chest and rib,4,N,NaN,None,[Acquired Abnormality],M95
3,C0001540,ENG,P,L0001540,PF,S0000200,N,A17838303,NaN,None,...,ICD10CM,PT,F43.24,Adjustment disorder with disturbance of conduct,4,N,256.0,None,[Mental or Behavioral Dysfunction],F43
4,C0002019,ENG,P,L0002019,PF,S0864547,N,A17777759,NaN,None,...,ICD10CM,PT,R48.0,Dyslexia and alexia,4,N,NaN,None,[Mental or Behavioral Dysfunction],R48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74255,C5926818,ENG,P,L19377448,PF,S23151269,Y,A36509185,NaN,None,...,ICD10CM,PT,Z68.56,"Body mass index [BMI] pediatric, greater than ...",4,N,NaN,None,[Finding],Z68
74256,C5926819,ENG,P,L19377464,PF,S23151397,Y,A36509067,NaN,None,...,ICD10CM,PT,Z83.72,Family history of familial adenomatous polyposis,4,N,256.0,None,[Finding],Z83
74257,C5926828,ENG,P,L19377646,PF,S23151355,N,A36509065,NaN,None,...,ICD10CM,PT,Z67.A2,Duffy a positive,4,N,NaN,None,[Laboratory or Test Result],Z67
74258,C5926831,ENG,P,L19377561,PF,S23151683,Y,A36508356,NaN,None,...,ICD10CM,PT,F50.84,Rumination disorder in adults,4,N,256.0,None,[Mental or Behavioral Dysfunction],F50
74259,C5926832,ENG,P,L19377714,PF,S23151475,N,A36508570,NaN,None,...,ICD10CM,PT,G40.843,"KCNQ2-related epilepsy, intractable, with stat...",4,N,NaN,None,[Disease or Syndrome],G40

In [19]:
umls_icd10_pt_df["CODE"].drop_duplicates()

0          O02.1
1          L73.0
2          M95.4
3         F43.24
4          R48.0
          ...
74255     Z68.56
74256     Z83.72
74257     Z67.A2
74258     F50.84
74259    G40.843
Name: CODE, Length: 74260, dtype: object

In [20]:
umls_icd10_pt_df["ICD10CMCode"] = umls_icd10_pt_df["CODE"].str.replace(".", "")
umls_icd10_pt_df[["ICD10CMCode", "CODE"]]

      ICD10CMCode     CODE
0            O021    O02.1
1            L730    L73.0
2            M954    M95.4
3           F4324   F43.24
4            R480    R48.0
...           ...      ...
74255       Z6856   Z68.56
74256       Z8372   Z83.72
74257       Z67A2   Z67.A2
74258       F5084   F50.84
74259      G40843  G40.843

[74260 rows x 2 columns]

### Use header terms to build a hierarchy for selecting subset of terms

In [21]:
umls_icd10_ht_sdf = spark.sql("""
select c.*
  from MRCONSO c
where SAB='ICD10CM' and TTY = 'HT' and CODE like '%-%'
and CODE != 'ICD-10-CM'
 order by CODE""")
umls_icd10_ht_df = umls_icd10_ht_sdf.toPandas()
umls_icd10_ht_df

,CUI,LAT,TS,LUI,STT,SUI,ISPREF,AUI,SAUI,SCUI,SDUI,SAB,TTY,CODE,STR,SRL,SUPPRESS,CVF,dummy
0,C0178238,ENG,S,L9592854,PF,S12054926,Y,A18910968,NaN,None,A00-A09,ICD10CM,HT,A00-A09,Intestinal infectious diseases (A00-A09),4,N,NaN,None
1,C0694449,ENG,P,L9596054,PF,S12053689,Y,A18905737,NaN,None,A00-B99,ICD10CM,HT,A00-B99,Certain infectious and parasitic diseases (A00...,4,N,NaN,None
2,C0041296,ENG,S,L9596452,PF,S12057645,Y,A18905738,NaN,None,A15-A19,ICD10CM,HT,A15-A19,Tuberculosis (A15-A19),4,N,NaN,None
3,C0348110,ENG,P,L9596055,PF,S12053690,Y,A18913607,NaN,None,A20-A28,ICD10CM,HT,A20-A28,Certain zoonotic bacterial diseases (A20-A28),4,N,NaN,None
4,C2939130,ENG,S,L9595709,PF,S12055760,Y,A18924111,NaN,None,A30-A49,ICD10CM,HT,A30-A49,Other bacterial diseases (A30-A49),4,N,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,C0582114,ENG,S,L9593329,PF,S12054430,Y,A18916194,NaN,None,Z66-Z66,ICD10CM,HT,Z66-Z66,Do not resuscitate status (Z66),4,N,NaN,None
314,C2911644,ENG,S,L9592711,PF,S12053460,Y,A18924105,NaN,None,Z67-Z67,ICD10CM,HT,Z67-Z67,Blood type (Z67),4,N,NaN,None
315,C2240399,ENG,S,L9594915,PF,S12919035,Y,A20115113,NaN,None,Z68-Z68,ICD10CM,HT,Z68-Z68,Body mass index [BMI] (Z68),4,N,NaN,None
316,C0178343,ENG,S,L9595246,PF,S12056675,Y,A18908291,NaN,None,Z69-Z76,ICD10CM,HT,Z69-Z76,Persons encountering health services in other ...,4,N,NaN,None
317,C0478618,ENG,S,L9595247,PF,S12056677,Y,A18913595,NaN,None,Z77-Z99,ICD10CM,HT,Z77-Z99,Persons with potential health hazards related ...,4,N,NaN,None

In [22]:
code_split_df = umls_icd10_ht_df["CODE"].str.split("-", expand=True)
code_split_df
start_letter = code_split_df[0].str.slice(stop=1)
start_number = code_split_df[0].str.slice(start=1)
end_letter = code_split_df[1].str.slice(stop=1)
end_number = code_split_df[1].str.slice(start=1)

umls_icd10_ht_parsed_df = umls_icd10_ht_df.copy()
umls_icd10_ht_parsed_df["start_range"] = code_split_df[0]
umls_icd10_ht_parsed_df["end_range"] = code_split_df[1]
umls_icd10_ht_parsed_df["start_letter"] = start_letter
umls_icd10_ht_parsed_df["start_number"] = start_number
umls_icd10_ht_parsed_df["end_letter"] = end_letter
umls_icd10_ht_parsed_df["end_number"] = end_number

umls_icd10_ht_parsed_df = umls_icd10_ht_parsed_df[["CUI", "CODE", "STR", "start_range", "start_letter", "start_number", "end_range", "end_letter", "end_number"]]
umls_icd10_ht_parsed_df

,CUI,CODE,STR,start_range,start_letter,start_number,end_range,end_letter,end_number
0,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A00,A,00,A09,A,09
1,C0694449,A00-B99,Certain infectious and parasitic diseases (A00...,A00,A,00,B99,B,99
2,C0041296,A15-A19,Tuberculosis (A15-A19),A15,A,15,A19,A,19
3,C0348110,A20-A28,Certain zoonotic bacterial diseases (A20-A28),A20,A,20,A28,A,28
4,C2939130,A30-A49,Other bacterial diseases (A30-A49),A30,A,30,A49,A,49
...,...,...,...,...,...,...,...,...,...
313,C0582114,Z66-Z66,Do not resuscitate status (Z66),Z66,Z,66,Z66,Z,66
314,C2911644,Z67-Z67,Blood type (Z67),Z67,Z,67,Z67,Z,67
315,C2240399,Z68-Z68,Body mass index [BMI] (Z68),Z68,Z,68,Z68,Z,68
316,C0178343,Z69-Z76,Persons encountering health services in other ...,Z69,Z,69,Z76,Z,76
317,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z77,Z,77,Z99,Z,99

In [24]:
letters = [chr(65 + i) for i in range(26)]
numbers = [("0" + str(i))[-2:]  for i in range(100)]
code_dict_list_expanded = []

for row_dict in umls_icd10_ht_parsed_df.to_dict(orient="records"):
  start_letter = row_dict["start_letter"]
  start_number = row_dict["start_number"]
  end_letter = row_dict["end_letter"]
  end_number = row_dict["end_number"]

  start_letter_i = letters.index(start_letter)
  end_letter_i = letters.index(end_letter)

  special_case = False
  codes_expanded = []
  try:
    int(start_number)
  except ValueError:
    special_case = True
    codes_expanded += [row_dict["start_range"]]

  if  not special_case:

    for i in range(start_letter_i, end_letter_i + 1):
      if start_letter == end_letter:
        try:
          int(end_number)
          codes_expanded += [f"{start_letter}{numbers[j]}" for j in range(int(start_number), int(end_number)+1)]

        except ValueError:
          codes_expanded += [f"{start_letter}{start_number}", f"{end_letter}{end_number}"]

      elif letters[i] == end_letter:
        codes_expanded += [f"{end_letter}{numbers[j]}" for j in range(0, int(end_number)+1)]
      elif letters[i] == start_letter:
        codes_expanded += [f"{letters[i]}{numbers[j]}" for j in range(int(start_number), 100)]
      else:
        codes_expanded += [f"{letters[i]}{numbers[j]}" for j in range(0, 100)]

  code_dict_list_expanded += [{"CUI": row_dict["CUI"], "CODE": row_dict["CODE"],
                               "STR": row_dict["STR"], "PREFIX_CODE": c} for c in codes_expanded]

codes_expanded_df = pd.DataFrame(code_dict_list_expanded)
codes_expanded_df

,CUI,CODE,STR,PREFIX_CODE
0,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A00
1,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A01
2,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A02
3,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A03
4,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A04
...,...,...,...,...
5407,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z95
5408,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z96
5409,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z97
5410,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z98
5411,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z99

In [61]:
joined_codes_expanded_df = codes_expanded_df.merge(umls_icd10_pt_df[["PREFIX_CODE"]], on="PREFIX_CODE").drop_duplicates()
joined_codes_expanded_df

,CUI,CODE,STR,PREFIX_CODE
0,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A00
3,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A01
14,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A02
25,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A03
31,C0178238,A00-A09,Intestinal infectious diseases (A00-A09),A04
...,...,...,...,...
176821,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z95
176834,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z96
176874,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z97
176887,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z98
176910,C0478618,Z77-Z99,Persons with potential health hazards related ...,Z99

In [23]:
!mkdir /content/drive/MyDrive/conceptsets/

mkdir: cannot create directory ‘/content/drive/MyDrive/conceptsets/’: File exists

In [25]:
joined_codes_expanded_df.to_csv("/content/drive/MyDrive/conceptsets/prefix_codes_icd10cm_expanded.csv", index=False)

In [65]:
ht_range_terms_icd10cm_df = joined_codes_expanded_df[["CUI", "CODE", "STR"]].drop_duplicates()
ht_range_terms_icd10cm_df

             CUI     CODE                                                STR
0       C0178238  A00-A09           Intestinal infectious diseases (A00-A09)
79      C0694449  A00-B99  Certain infectious and parasitic diseases (A00...
1146    C0041296  A15-A19                             Tuberculosis (A15-A19)
1197    C0348110  A20-A28      Certain zoonotic bacterial diseases (A20-A28)
1244    C2939130  A30-A49                 Other bacterial diseases (A30-A49)
...          ...      ...                                                ...
176243  C0582114  Z66-Z66                    Do not resuscitate status (Z66)
176244  C2911644  Z67-Z67                                   Blood type (Z67)
176258  C2240399  Z68-Z68                        Body mass index [BMI] (Z68)
176290  C0178343  Z69-Z76  Persons encountering health services in other ...
176375  C0478618  Z77-Z99  Persons with potential health hazards related ...

[318 rows x 3 columns]

In [66]:
ht_range_terms_icd10cm_df.to_csv("/content/drive/MyDrive/conceptsets/ht_range_terms_icd10cm.csv", index=False)

## Load OHDSI CDM Concept tables

In [26]:
concept_tables_path_dict = {
    "concept": {
        "concept": "/content/drive/MyDrive/OHDSI/vocabulary/20250317/export/concept.parquet",
        "concept_ancestor": "/content/drive/MyDrive/OHDSI/vocabulary/20250317/export/concept_ancestor.parquet",
        "concept_class": "/content/drive/MyDrive/OHDSI/vocabulary/20250317/export/concept_class.parquet",
        "concept_relationship": "/content/drive/MyDrive/OHDSI/vocabulary/20250317/export/concept_relationship.parquet",
        "concept_synonym": "/content/drive/MyDrive/OHDSI/vocabulary/20250317/export/concept_synonym.parquet",
        "domain": "/content/drive/MyDrive/OHDSI/vocabulary/20250317/export/domain.parquet",
        "drug_strength": "/content/drive/MyDrive/OHDSI/vocabulary/20250317/export/drug_strength.parquet",
        "relationship": "/content/drive/MyDrive/OHDSI/vocabulary/20250317/export/relationship.parquet",
        "vocabulary": "/content/drive/MyDrive/OHDSI/vocabulary/20250317/export/vocabulary.parquet"
    }
}

In [27]:
concept_tables_dict = load_tables(spark, concept_tables_path_dict, ["concept"])

Loading domain: concept
Loading table: concept
Loading table: concept_ancestor
Loading table: concept_class
Loading table: concept_relationship
Loading table: concept_synonym
Loading table: domain
Loading table: drug_strength
Loading table: relationship
Loading table: vocabulary

### Extract ICD10CM from OHDSI concept tables

In [28]:
icd10cm_sdf = spark.sql("""with c_icd10cm as (
  select * from concept c where c.vocabulary_id = 'ICD10CM')
select * from c_icd10cm
""")
icd10cm_sdf.createOrReplaceTempView("icd10cm")
icd10cm_df = icd10cm_sdf.toPandas()
icd10cm_df

,concept_id,concept_name,domain_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason,vocabulary_id
0,45535298,Torus fracture of lower end of unspecified rad...,Condition,7-char billing code,None,S52.529G,19700101,20991231,None,ICD10CM
1,45564107,Colles' fracture,Condition,5-char nonbill code,None,S52.53,20061230,20991231,None,ICD10CM
2,45535299,"Colles' fracture of right radius, initial enco...",Condition,7-char billing code,None,S52.531B,19700101,20991231,None,ICD10CM
3,45583481,"Colles' fracture of right radius, subsequent e...",Condition,7-char billing code,None,S52.531D,19700101,20991231,None,ICD10CM
4,45578601,"Colles' fracture of right radius, subsequent e...",Condition,7-char billing code,None,S52.531E,19700101,20991231,None,ICD10CM
...,...,...,...,...,...,...,...,...,...,...
99416,1576248,Acquired absence of upper limb below elbow,Condition,5-char nonbill code,None,Z89.21,20120101,20991231,None,ICD10CM
99417,45542497,Cochlear implant status,Observation,5-char billing code,None,Z96.21,19700101,20991231,None,ICD10CM
99418,785989,"Foreign body sensation, right eye",Condition,6-char billing code,None,H57.8A1,20231001,20991231,None,ICD10CM
99419,786104,Sagittal craniosynostosis,Condition,5-char billing code,None,Q75.01,20231001,20991231,None,ICD10CM
99420,786249,Magnetic metal jewelry entering into or throug...,Condition,5-char nonbill code,None,W44.D4,20231001,20991231,None,ICD10CM

In [29]:
umls_ohdsi_icd10_pt_df = umls_icd10_pt_df.merge(icd10cm_df[["concept_code","concept_id", "domain_id"]], left_on="CODE", right_on="concept_code", how="inner")

In [30]:
umls_ohdsi_icd10_pt_df

,CUI,LAT,TS,LUI,STT,SUI,ISPREF,AUI,SAUI,SCUI,...,SRL,SUPPRESS,CVF,dummy,STYs,PREFIX_CODE,ICD10CMCode,concept_code,concept_id,domain_id
0,C0000814,ENG,P,L0000814,PF,S0218595,N,A17815492,NaN,None,...,4,N,256.0,None,[Disease or Syndrome],O02,O021,O02.1,35209522,Condition
1,C0001145,ENG,P,L0001145,VC,S0798036,N,A17839636,NaN,None,...,4,N,256.0,None,[Disease or Syndrome],L73,L730,L73.0,35208638,Observation
2,C0001171,ENG,P,L0001171,PF,S0218783,N,A17866282,NaN,None,...,4,N,NaN,None,[Acquired Abnormality],M95,M954,M95.4,35209145,Condition
3,C0001540,ENG,P,L0001540,PF,S0000200,N,A17838303,NaN,None,...,4,N,256.0,None,[Mental or Behavioral Dysfunction],F43,F4324,F43.24,45600747,Condition
4,C0002019,ENG,P,L0002019,PF,S0864547,N,A17777759,NaN,None,...,4,N,NaN,None,[Mental or Behavioral Dysfunction],R48,R480,R48.0,35211378,Condition
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74255,C5926818,ENG,P,L19377448,PF,S23151269,Y,A36509185,NaN,None,...,4,N,NaN,None,[Finding],Z68,Z6856,Z68.56,1102847,Observation
74256,C5926819,ENG,P,L19377464,PF,S23151397,Y,A36509067,NaN,None,...,4,N,256.0,None,[Finding],Z83,Z8372,Z83.72,1102848,Observation
74257,C5926828,ENG,P,L19377646,PF,S23151355,N,A36509065,NaN,None,...,4,N,NaN,None,[Laboratory or Test Result],Z67,Z67A2,Z67.A2,1102825,Condition
74258,C5926831,ENG,P,L19377561,PF,S23151683,Y,A36508356,NaN,None,...,4,N,256.0,None,[Mental or Behavioral Dysfunction],F50,F5084,F50.84,1102672,Condition
74259,C5926832,ENG,P,L19377714,PF,S23151475,N,A36508570,NaN,None,...,4,N,NaN,None,[Disease or Syndrome],G40,G40843,G40.843,1102676,Condition

In [31]:
umls_ohdsi_icd10_pt_df.to_csv("/content/drive/MyDrive/conceptsets/umls_ohdsi_icd10_pt.csv", index=False)

In [32]:
umls_ohdsi_icd10_pt_df["ICD10CMCode"].drop_duplicates()

0          O021
1          L730
2          M954
3         F4324
4          R480
          ...
74255     Z6856
74256     Z8372
74257     Z67A2
74258     F5084
74259    G40843
Name: ICD10CMCode, Length: 74260, dtype: object

### Connect comorbidities to UMLS & OHDSI Concept tables

In [33]:
com_df = pd.merge(umls_ohdsi_icd10_pt_df, charlson_merged_df, left_on="ICD10CMCode", right_on="Code", how="inner")

In [34]:
elh_df = pd.merge(umls_ohdsi_icd10_pt_df, elix_hauser_merged_df, left_on="ICD10CMCode", right_on="Code", how="inner")

In [35]:
com_df_cols = list(com_df.columns)

In [36]:

def generate_coding(df, columns):
  union_df = {}
  for c in columns:
    union_df[c] = df.copy()[df[c] == 1][["CODE","STR", "concept_id"]]
    union_df[c].columns = ["code", "description", "concept_id"]
    union_df[c]["code_type"] = "ICD10CM"
    union_df[c]["code_class"] = c

    union_df[c] = union_df[c][["code", "code_type", "description", "concept_id", "code_class"]]

  return pd.concat(union_df, axis=0)

In [37]:
charlson_code_export_df = generate_coding(com_df, com_df_cols)
charlson_code_export_df

/tmp/ipython-input-36-1933799129.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  union_df[c]["code_type"] = "ICD10CM"
/tmp/ipython-input-36-1933799129.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  union_df[c]["code_class"] = c
/tmp/ipython-input-36-1933799129.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  union_df[c]["code_type"] = "ICD10CM"
/tmp/ipython-input-36-1933799129.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  union_df[c]["code_class"] = c

                  code code_type  \
id       36374   A00.0   ICD10CM
mi       5602   I21.21   ICD10CM
         14414   I22.0   ICD10CM
         14415   I22.9   ICD10CM
         17093   I22.1   ICD10CM
...                ...       ...
metacanc 63303  C79.62   ICD10CM
         63423  C78.39   ICD10CM
         65014  C78.01   ICD10CM
         65015  C79.00   ICD10CM
aids     8710      B20   ICD10CM

                                                      description  concept_id  \
id       36374  Cholera due to Vibrio cholerae 01, biovar chol...    35205396
mi       5602   ST elevation (STEMI) myocardial infarction inv...    45572080
         14414  Subsequent ST elevation (STEMI) myocardial inf...    35207686
         14415  Subsequent ST elevation (STEMI) myocardial inf...    35207689
         17093  Subsequent ST elevation (STEMI) myocardial inf...    35207687
...                                                           ...         ...
metacanc 63303         Secondary malignant neoplasm of left ovary    45571541
         63423  Secondary malignant neoplasm of other respirat...    45557015
         65014         Secondary malignant neoplasm of right lung    45537840
         65015  Secondary malignant neoplasm of unspecified ki...    45576341
aids     8710          Human immunodeficiency virus [HIV] disease    35205776

               code_class
id       36374         id
mi       5602          mi
         14414         mi
         14415         mi
         17093         mi
...                   ...
metacanc 63303   metacanc
         63423   metacanc
         65014   metacanc
         65015   metacanc
aids     8710        aids

[2607 rows x 5 columns]

In [38]:
elh_columns = list(elh_df.columns)
elih_columns = elh_columns[elh_columns.index("chf"):]
elih_columns

['chf',
 'carit',
 'valv',
 'pcd',
 'pvd',
 'hypunc',
 'hypc',
 'para',
 'ond',
 'cpd',
 'diabunc',
 'diabc',
 'hypothy',
 'rf',
 'ld',
 'pud',
 'aids',
 'lymph',
 'metacanc',
 'solidtum',
 'rheumd',
 'coag',
 'obes',
 'wloss',
 'fed',
 'blane',
 'dane',
 'alcohol',
 'drug',
 'psycho',
 'depre']

In [39]:
elixhauser_code_export_df = generate_coding(elh_df, elih_columns)
elixhauser_code_export_df

/tmp/ipython-input-36-1933799129.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  union_df[c]["code_type"] = "ICD10CM"
/tmp/ipython-input-36-1933799129.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  union_df[c]["code_class"] = c

                code code_type  \
chf   558      P29.0   ICD10CM
      835      I11.0   ICD10CM
      5609    I50.40   ICD10CM
      5610    I50.43   ICD10CM
      8473   I50.812   ICD10CM
...              ...       ...
depre 62607    F33.0   ICD10CM
      62608    F33.1   ICD10CM
      68140   F31.31   ICD10CM
      68142   F33.40   ICD10CM
      68145   F43.29   ICD10CM

                                                   description  concept_id  \
chf   558                             Neonatal cardiac failure    35210517
      835        Hypertensive heart disease with heart failure    35207669
      5609   Unspecified combined systolic (congestive) and...    45533457
      5610   Acute on chronic combined systolic (congestive...    45567181
      8473                         Chronic right heart failure     1326603
...                                                        ...         ...
depre 62607         Major depressive disorder, recurrent, mild    35207156
      62608     Major depressive disorder, recurrent, moderate    35207157
      68140  Bipolar disorder, current episode depressed, mild    45566839
      68142  Major depressive disorder, recurrent, in remis...    45547706
      68145            Adjustment disorder with other symptoms    45576547

            code_class
chf   558          chf
      835          chf
      5609         chf
      5610         chf
      8473         chf
...                ...
depre 62607      depre
      62608      depre
      68140      depre
      68142      depre
      68145      depre

[3203 rows x 5 columns]

In [40]:
charlson_code_export_df.to_csv("/content/drive/MyDrive/conceptsets/charlson_codes.csv", index=False)

In [41]:
elixhauser_code_export_df.to_csv("/content/drive/MyDrive/conceptsets/elixhauser_codes.csv", index=False)

### Extract CCSR terms

In [42]:
sabs_df = spark.sql("select distinct SAB from MRCONSO").toPandas()
sabs_df[sabs_df.SAB.str.contains("CCSR")]

              SAB
26   CCSR_ICD10CM
47  CCSR_ICD10PCS

In [43]:
ccsr_umls_df = spark.sql("select * from MRCONSO where SAB='CCSR_ICD10CM' and TTY='SD'").toPandas()[["CODE", "STR"]]
ccsr_umls_df.columns = ["code", "description"]
ccsr_umls_df["code_type"] = "CCSR_ICD10CM"
ccsr_umls_df = ccsr_umls_df[["code", "code_type", "description"]]
ccsr_umls_df = ccsr_umls_df.sort_values(by="code")
ccsr_umls_df

       code     code_type                          description
527  BLD001  CCSR_ICD10CM                   Nutritional anemia
393  BLD002  CCSR_ICD10CM                     Hemolytic anemia
392  BLD003  CCSR_ICD10CM                      Aplastic anemia
497  BLD004  CCSR_ICD10CM         Acute posthemorrhagic anemia
110  BLD005  CCSR_ICD10CM             Sickle cell trait/anemia
..      ...           ...                                  ...
347  SYM016  CCSR_ICD10CM     Other general signs and symptoms
212  SYM017  CCSR_ICD10CM  Abnormal findings without diagnosis
340  SYM018  CCSR_ICD10CM                          Prediabetes
545  XXX000  CCSR_ICD10CM                     Unacceptable PDX
546  XXX111  CCSR_ICD10CM                     Unacceptable DX1

[554 rows x 3 columns]

In [44]:
ccsr_umls_df.to_csv("/content/drive/MyDrive/conceptsets/ccsr_codes.csv", index=False)

## Mapping ICD10CM to SNOMED

### Building maps

In [45]:
snomed_sdf = spark.sql("""with c_snomed as (
  select * from concept c where c.vocabulary_id = 'SNOMED')
select * from c_snomed
""")

In [46]:
concept_map_sdf = spark.sql("""with c_icd10cm as (
  select * from concept c where c.vocabulary_id = 'ICD10CM'),
    c_snomed as (
      select * from concept c where c.vocabulary_id = 'SNOMED')
  select distinct ci.concept_id, ci.concept_name, ci.domain_id, ci.concept_code, ci.domain_id, ci.concept_class_id,
    ci.vocabulary_id,
    cs.concept_id as mapped_concept_id, cs.concept_name as mapped_concept_name, cs.domain_id as mapped_domain_id,
    cs.concept_code as mapped_concept_code,
    cs.concept_class_id as mapped_concept_class_id, cs.vocabulary_id as mapped_vocabulary_id
  from c_icd10cm ci
  join concept_relationship cr on cr.concept_id_1 = ci.concept_id
  join c_snomed cs on cs.concept_id = cr.concept_id_2
  and cr.relationship_id = 'Maps to'
    """
)
concept_map_sdf.createOrReplaceTempView("concept_map")
concept_map_sdf.toPandas()

,concept_id,concept_name,domain_id,concept_code,domain_id,concept_class_id,vocabulary_id,mapped_concept_id,mapped_concept_name,mapped_domain_id,mapped_concept_code,mapped_concept_class_id,mapped_vocabulary_id
0,35206181,Malignant neoplasm of overlapping sites of larynx,Condition,C32.8,Condition,4-char billing code,ICD10CM,22839,Overlapping malignant neoplasm of larynx,Condition,109369002,Disorder,SNOMED
1,35210612,Other neonatal hypoglycemia,Condition,P70.4,Condition,4-char billing code,ICD10CM,23034,Neonatal hypoglycemia,Condition,52767006,Disorder,SNOMED
2,35205603,Chlamydial infection of pharynx,Condition,A56.4,Condition,4-char billing code,ICD10CM,23137,Chlamydial pharyngitis,Condition,232403001,Disorder,SNOMED
3,1572082,Congenital malformations of esophagus,Condition,Q39,Condition,3-char nonbill code,ICD10CM,23868,Congenital anomaly of esophagus,Condition,69771008,Disorder,SNOMED
4,35210926,Other congenital malformations of esophagus,Condition,Q39.8,Condition,4-char billing code,ICD10CM,23868,Congenital anomaly of esophagus,Condition,69771008,Disorder,SNOMED
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127981,45596736,"Pathological fracture in neoplastic disease, l...",Condition,M84.564G,Condition,7-char billing code,ICD10CM,45766973,Pathologic fracture of fibula at site of neoplasm,Condition,704252008,Disorder,SNOMED
127982,45601603,"Pathological fracture in neoplastic disease, r...",Condition,M84.551G,Condition,7-char billing code,ICD10CM,45766974,Pathologic fracture of femur at site of neoplasm,Condition,704253003,Disorder,SNOMED
127983,45606330,Age-related osteoporosis with current patholog...,Condition,M80.041K,Condition,7-char billing code,ICD10CM,45767040,Osteoporotic fracture of hand,Condition,704333004,Disorder,SNOMED
127984,45572557,Age-related osteoporosis with current patholog...,Condition,M80.022K,Condition,7-char billing code,ICD10CM,45767042,Osteoporotic fracture of humerus,Condition,704335006,Disorder,SNOMED
127985,1568663,Combined forms of infantile and juvenile cataract,Condition,H26.06,Condition,5-char nonbill code,ICD10CM,45770919,Infantile and/or juvenile cataract,Condition,342291000119102,Disorder,SNOMED

In [47]:
concept_map_sdf.select("mapped_concept_id").drop_duplicates().toPandas()

       mapped_concept_id
0                 443881
1               40481568
2               37170760
3               37170865
4                 441201
...                  ...
14690            4338523
14691           40651279
14692             261514
14693           35625971
14694           37016767

[14695 rows x 1 columns]

In [48]:
concept_map_df = concept_map_sdf.toPandas()

### Elixhauser mapped

In [49]:
elixhauser_code_map_snomed_export_df = elixhauser_code_export_df.merge(concept_map_df, on = "concept_id", how="inner").sort_values(by=["code_class", "code", "mapped_concept_id"])
elixhauser_code_map_snomed_export_df

,code,code_type,description,concept_id,code_class,concept_name,domain_id,concept_code,domain_id,concept_class_id,vocabulary_id,mapped_concept_id,mapped_concept_name,mapped_domain_id,mapped_concept_code,mapped_concept_class_id,mapped_vocabulary_id
1551,B20,ICD10CM,Human immunodeficiency virus [HIV] disease,35205776,aids,Human immunodeficiency virus [HIV] disease,Condition,B20,Condition,3-char billing code,ICD10CM,439727,Human immunodeficiency virus infection,Condition,86406008,Disorder,SNOMED
3646,E52,ICD10CM,Niacin deficiency [pellagra],35206985,alcohol,Niacin deficiency [pellagra],Condition,E52,Condition,3-char billing code,ICD10CM,4303664,Niacin deficiency,Condition,418279001,Disorder,SNOMED
3754,F10.10,ICD10CM,"Alcohol abuse, uncomplicated",45595845,alcohol,"Alcohol abuse, uncomplicated",Condition,F10.10,Condition,5-char billing code,ICD10CM,433753,Alcohol abuse,Condition,15167005,Disorder,SNOMED
3671,F10.11,ICD10CM,"Alcohol abuse, in remission",1326497,alcohol,"Alcohol abuse, in remission",Condition,F10.11,Condition,5-char billing code,ICD10CM,433753,Alcohol abuse,Condition,15167005,Disorder,SNOMED
3672,F10.11,ICD10CM,"Alcohol abuse, in remission",1326497,alcohol,"Alcohol abuse, in remission",Condition,F10.11,Condition,5-char billing code,ICD10CM,35622958,Disorder in remission,Condition,765205004,Disorder,SNOMED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3577,E44.1,ICD10CM,Mild protein-calorie malnutrition,35206969,wloss,Mild protein-calorie malnutrition,Condition,E44.1,Condition,4-char billing code,ICD10CM,4096196,Mild protein-calorie malnutrition (weight for ...,Condition,190603003,Disorder,SNOMED
3572,E45,ICD10CM,Retarded development following protein-calorie...,35206970,wloss,Retarded development following protein-calorie...,Condition,E45,Condition,3-char billing code,ICD10CM,435773,Arrested development following protein-calorie...,Condition,74257000,Disorder,SNOMED
3571,E46,ICD10CM,Unspecified protein-calorie malnutrition,35206971,wloss,Unspecified protein-calorie malnutrition,Condition,E46,Condition,3-char billing code,ICD10CM,4276360,Undernutrition,Condition,65404009,Disorder,SNOMED
3570,R63.4,ICD10CM,Abnormal weight loss,35211409,wloss,Abnormal weight loss,Observation,R63.4,Observation,4-char billing code,ICD10CM,435928,Abnormal weight loss,Observation,267024001,Clinical Finding,SNOMED
3568,R64,ICD10CM,Cachexia,35211413,wloss,Cachexia,Condition,R64,Condition,3-char billing code,ICD10CM,134765,Cachexia,Condition,238108007,Clinical Finding,SNOMED

In [50]:
elixhauser_code_map_snomed_export_df.to_csv("/content/drive/MyDrive/conceptsets/elixhauser_codes_map_snomed.csv", index=False)

In [51]:
charlson_code__map_snomed_export_df = charlson_code_export_df.merge(concept_map_df, on = "concept_id", how="inner").sort_values(by=["code_class", "code", "mapped_concept_id"])
charlson_code__map_snomed_export_df

,code,code_type,description,concept_id,code_class,concept_name,domain_id,concept_code,domain_id,concept_class_id,vocabulary_id,mapped_concept_id,mapped_concept_name,mapped_domain_id,mapped_concept_code,mapped_concept_class_id,mapped_vocabulary_id
3501,B20,ICD10CM,Human immunodeficiency virus [HIV] disease,35205776,aids,Human immunodeficiency virus [HIV] disease,Condition,B20,Condition,3-char billing code,ICD10CM,439727,Human immunodeficiency virus infection,Condition,86406008,Disorder,SNOMED
2607,C00.0,ICD10CM,Malignant neoplasm of external upper lip,35206047,canc,Malignant neoplasm of external upper lip,Condition,C00.0,Condition,4-char billing code,ICD10CM,138074,Primary malignant neoplasm of vermilion border...,Condition,372027002,Disorder,SNOMED
2892,C00.1,ICD10CM,Malignant neoplasm of external lower lip,35206048,canc,Malignant neoplasm of external lower lip,Condition,C00.1,Condition,4-char billing code,ICD10CM,132565,Primary malignant neoplasm of vermilion border...,Condition,372026006,Disorder,SNOMED
2468,C00.2,ICD10CM,"Malignant neoplasm of external lip, unspecified",35206049,canc,"Malignant neoplasm of external lip, unspecified",Condition,C00.2,Condition,4-char billing code,ICD10CM,133969,Primary malignant neoplasm of vermilion border...,Condition,94135007,Disorder,SNOMED
2754,C00.3,ICD10CM,"Malignant neoplasm of upper lip, inner aspect",35206050,canc,"Malignant neoplasm of upper lip, inner aspect",Condition,C00.3,Condition,4-char billing code,ICD10CM,138351,Primary malignant neoplasm of inner aspect of ...,Condition,93837005,Disorder,SNOMED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1539,M34.89,ICD10CM,Other systemic sclerosis,45572448,rheumd,Other systemic sclerosis,Condition,M34.89,Condition,5-char billing code,ICD10CM,134442,Systemic sclerosis,Condition,89155008,Disorder,SNOMED
1048,M34.9,ICD10CM,"Systemic sclerosis, unspecified",35208831,rheumd,"Systemic sclerosis, unspecified",Condition,M34.9,Condition,4-char billing code,ICD10CM,134442,Systemic sclerosis,Condition,89155008,Disorder,SNOMED
1348,M35.1,ICD10CM,Other overlap syndromes,35208832,rheumd,Other overlap syndromes,Condition,M35.1,Condition,4-char billing code,ICD10CM,4079978,Overlap syndrome,Condition,276657008,Disorder,SNOMED
1264,M35.3,ICD10CM,Polymyalgia rheumatica,35208834,rheumd,Polymyalgia rheumatica,Condition,M35.3,Condition,4-char billing code,ICD10CM,255348,Polymyalgia rheumatica,Condition,65323003,Disorder,SNOMED
1050,M36.0,ICD10CM,Dermato(poly)myositis in neoplastic disease,35208841,rheumd,Dermato(poly)myositis in neoplastic disease,Condition,M36.0,Condition,4-char billing code,ICD10CM,4344161,Dermatomyositis with malignant disease,Condition,239901009,Disorder,SNOMED

In [52]:
charlson_code__map_snomed_export_df.to_csv("/content/drive/MyDrive/conceptsets/charlson_codes_map_snomed.csv", index=False)

In [53]:
mapped_concept_ids_sdf = concept_map_sdf.select("mapped_concept_id").drop_duplicates()
mapped_concept_ids_sdf.createOrReplaceTempView("mapped_concept_ids")
mapped_concept_ids_sdf.toPandas()

       mapped_concept_id
0                 443881
1               40481568
2               37170760
3               37170865
4                 441201
...                  ...
14690            4338523
14691           40651279
14692             261514
14693           35625971
14694           37016767

[14695 rows x 1 columns]

In [54]:
snomed_descendant_concept_map_sdf = spark.sql("""
select c1.concept_id, c1.concept_name, c1.vocabulary_id, c1.domain_id,
  ca.descendant_concept_id, c2.concept_name as descendant_concept_name,
  c2.concept_code as descendant_concept_code,
  c2.vocabulary_id as descendant_vocabulary_id, c2.domain_id as descendant_domain_id,
  min_levels_of_separation,
  max_levels_of_separation
from concept_ancestor ca
  join mapped_concept_ids mic on ca.ancestor_concept_id = mic.mapped_concept_id
  join concept c1 on c1.concept_id = ca.ancestor_concept_id
  join concept c2 on c2.concept_id = ca.descendant_concept_id
  where  c1.concept_id != c2.concept_id and c1.vocabulary_id = c2.vocabulary_id
  order by c1.concept_id, min_levels_of_separation, c2.concept_id

  """)

In [55]:
snomed_descendant_concept_map_df = snomed_descendant_concept_map_sdf.toPandas()

In [56]:
snomed_descendant_concept_map_sdf.where(F.col("concept_id") == F.lit(439727)).toPandas()

,concept_id,concept_name,vocabulary_id,domain_id,descendant_concept_id,descendant_concept_name,descendant_concept_code,descendant_vocabulary_id,descendant_domain_id,min_levels_of_separation,max_levels_of_separation
0,439727,Human immunodeficiency virus infection,SNOMED,Condition,432554,Human immunodeficiency virus II infection,79019005,SNOMED,Condition,1,1
1,439727,Human immunodeficiency virus infection,SNOMED,Condition,606040,Primary human immunodeficiency virus infection,1142045004,SNOMED,Condition,1,1
2,439727,Human immunodeficiency virus infection,SNOMED,Condition,3654682,Chronic hepatitis C co-occurrent with human im...,838377003,SNOMED,Condition,1,1
3,439727,Human immunodeficiency virus infection,SNOMED,Condition,4008081,Acute HIV infection,111880001,SNOMED,Condition,1,1
4,439727,Human immunodeficiency virus infection,SNOMED,Condition,4180254,Congenital human immunodeficiency virus infection,52079000,SNOMED,Condition,1,1
...,...,...,...,...,...,...,...,...,...,...,...
193,439727,Human immunodeficiency virus infection,SNOMED,Condition,4225170,Histoplasmosis with AIDS (acquired immunodefic...,420945005,SNOMED,Condition,5,5
194,439727,Human immunodeficiency virus infection,SNOMED,Condition,4227380,Disseminated candidiasis with AIDS (acquired i...,421077004,SNOMED,Condition,5,5
195,439727,Human immunodeficiency virus infection,SNOMED,Condition,4227539,Herpes zoster with AIDS (acquired immunodefici...,422127002,SNOMED,Condition,5,5
196,439727,Human immunodeficiency virus infection,SNOMED,Condition,4228612,Encephalomyelitis with AIDS (acquired immunode...,422089004,SNOMED,Condition,5,7
197,439727,Human immunodeficiency virus infection,SNOMED,Condition,4226658,Tuberculosis with AIDS (acquired immunodeficie...,421571007,SNOMED,Condition,6,6

In [57]:
snomed_descendant_concept_map_sdf.where(F.col("concept_id") == F.lit(439727)).alias("ca").join(concept_map_sdf.alias("cm"),
                                                                                               F.col("ca.descendant_concept_id") == F.col("cm.mapped_concept_id")).select("ca.*", "cm.*").toPandas()

,concept_id,concept_name,vocabulary_id,domain_id,descendant_concept_id,descendant_concept_name,descendant_concept_code,descendant_vocabulary_id,descendant_domain_id,min_levels_of_separation,...,concept_code,domain_id,concept_class_id,vocabulary_id,mapped_concept_id,mapped_concept_name,mapped_domain_id,mapped_concept_code,mapped_concept_class_id,mapped_vocabulary_id
0,439727,Human immunodeficiency virus infection,SNOMED,Condition,432554,Human immunodeficiency virus II infection,79019005,SNOMED,Condition,1,...,B97.35,Condition,5-char billing code,ICD10CM,432554,Human immunodeficiency virus II infection,Condition,79019005,Disorder,SNOMED
1,439727,Human immunodeficiency virus infection,SNOMED,Condition,36715476,Human immunodeficiency virus complicating preg...,721166000,SNOMED,Condition,1,...,O98.713,Condition,6-char billing code,ICD10CM,36715476,Human immunodeficiency virus complicating preg...,Condition,721166000,Disorder,SNOMED
2,439727,Human immunodeficiency virus infection,SNOMED,Condition,36715476,Human immunodeficiency virus complicating preg...,721166000,SNOMED,Condition,1,...,O98.73,Condition,5-char billing code,ICD10CM,36715476,Human immunodeficiency virus complicating preg...,Condition,721166000,Disorder,SNOMED
3,439727,Human immunodeficiency virus infection,SNOMED,Condition,36715476,Human immunodeficiency virus complicating preg...,721166000,SNOMED,Condition,1,...,O98.711,Condition,6-char billing code,ICD10CM,36715476,Human immunodeficiency virus complicating preg...,Condition,721166000,Disorder,SNOMED
4,439727,Human immunodeficiency virus infection,SNOMED,Condition,36715476,Human immunodeficiency virus complicating preg...,721166000,SNOMED,Condition,1,...,O98.71,Condition,5-char nonbill code,ICD10CM,36715476,Human immunodeficiency virus complicating preg...,Condition,721166000,Disorder,SNOMED
5,439727,Human immunodeficiency virus infection,SNOMED,Condition,36715476,Human immunodeficiency virus complicating preg...,721166000,SNOMED,Condition,1,...,O98.719,Condition,6-char billing code,ICD10CM,36715476,Human immunodeficiency virus complicating preg...,Condition,721166000,Disorder,SNOMED
6,439727,Human immunodeficiency virus infection,SNOMED,Condition,36715476,Human immunodeficiency virus complicating preg...,721166000,SNOMED,Condition,1,...,O98.712,Condition,6-char billing code,ICD10CM,36715476,Human immunodeficiency virus complicating preg...,Condition,721166000,Disorder,SNOMED
7,439727,Human immunodeficiency virus infection,SNOMED,Condition,36715476,Human immunodeficiency virus complicating preg...,721166000,SNOMED,Condition,1,...,O98.7,Condition,4-char nonbill code,ICD10CM,36715476,Human immunodeficiency virus complicating preg...,Condition,721166000,Disorder,SNOMED
8,439727,Human immunodeficiency virus infection,SNOMED,Condition,45757132,Human immunodeficiency virus in mother complic...,10755671000119100,SNOMED,Condition,2,...,O98.72,Condition,5-char billing code,ICD10CM,45757132,Human immunodeficiency virus in mother complic...,Condition,10755671000119100,Disorder,SNOMED
9,439727,Human immunodeficiency virus infection,SNOMED,Condition,4241530,Asymptomatic human immunodeficiency virus infe...,91947003,SNOMED,Condition,1,...,Z21,Condition,3-char billing code,ICD10CM,4241530,Asymptomatic human immunodeficiency virus infe...,Condition,91947003,Disorder,SNOMED